Exemplo_App_NetCore_Dapper/Models/ErrorViewModel.cs
using System;

namespace Exemplo_App_NetCore_Dapper.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Exemplo_App_NetCore_Dapper/Models/Veiculo_Marca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Exemplo_App_NetCore_Dapper.Models
{
    public class Veiculo_Marca
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(100)]
        [Required]
        public string Marca { get; set; }

        public virtual List<Veiculo_Modelo> Modelos { get; set; }
    }
}

Exemplo_App_NetCore_Dapper/Models/Veiculo_Modelo.cs
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Exemplo_App_NetCore_Dapper.Models
{
    [Table("Veiculo_Modelo")] //A extensão Dapper.Contrib, pluraliza os nomes das tabelas, então temos que forçar o nome no DataAnnotations
    public class Veiculo_Modelo
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string Nome { get; set; }

        [Required]
        public int Ano { get; set; }

        [Required]
        [MaxLength(100)]
        public string Tipo { get; set; }

        [Required]
        public double PrecoFipe { get; set; }

        [Required]
        public int MarcaId { get; set; }

        [Write(false)] // atributo do Dapper para excluir essa propriedade nas querys do banco (inserts, updates etc..)
        public virtual Veiculo_Marca Dados_Marca { get; set; }
    }
}

Exemplo_App_NetCore_Dapper/Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exemplo_App_NetCore_Dapper.Models;
using Exemplo_App_NetCore_Dapper.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace Exemplo_App_NetCore_Dapper.Controllers
{
    public class VeiculosController : Controller
    {
        private IVeiculosRepository _veiculoRepository;

        //DI
        public VeiculosController(IVeiculosRepository veiculoRepository)
        {
            this._veiculoRepository = veiculoRepository;
        }
        // GET: Veiculos
        public ActionResult Index()
        {
            return View(_veiculoRepository.GetModelos());
        }

        // GET: Veiculos/Details/5
        public ActionResult Details(int id)
        {
            return View(_veiculoRepository.Get(id));
        }

        // GET: Veiculos/Create
        public ActionResult Create()
        {
            ViewBag.Marcas = new SelectList(_veiculoRepository.GetMarcas(), "Id", "Marca");
            return View();
        }

        // POST: Veiculos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection, Veiculo_Modelo modelo)
        {
            try
            {
                modelo.MarcaId = Convert.ToInt32(collection["Marca"]);
                _veiculoRepository.Add(modelo);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Veiculos/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Marcas = new SelectList(_veiculoRepository.GetMarcas(), "Id", "Marca");
            Veiculo_Modelo modelo = _veiculoRepository.Get(id);
            return View(modelo);
        }

        // POST: Veiculos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection, Veiculo_Modelo modelo)
        {
            try
            {
                modelo.MarcaId = Convert.ToInt32(collection["Marca"]);
                _veiculoRepository.Edit(modelo);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: Veiculos/Delete/5
        public ActionResult Delete(int id)
        {
            _veiculoRepository.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Exemplo_App_NetCore_Dapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exemplo_App_NetCore_Dapper</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Veiculos" asp-action="Index" class="navbar-brand">Cadastro Utilizando Dapper</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Veiculos" asp-action="Index">Início</a></li>
                    <li><a asp-area="" asp-controller="Veiculos" asp-action="Index">Detalhes</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Exemplo_App_NetCore_Dapper _ By César Ferreira</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Exemplo_App_NetCore_Dapper/Views/Veiculos/Create.cshtml
@model Exemplo_App_NetCore_Dapper.Models.Veiculo_Modelo

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Veiculo_Modelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.DropDownList("Marca", ViewBag.Marcas as SelectList)

                @Html.HiddenFor(item => item.Dados_Marca)
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoFipe" class="control-label"></label>
                <input asp-for="PrecoFipe" class="form-control" />
                <span asp-validation-for="PrecoFipe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Exemplo_App_NetCore_Dapper/Views/Veiculos/Details.cshtml
@model Exemplo_App_NetCore_Dapper.Models.Veiculo_Modelo

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Veiculo_Modelo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PrecoFipe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrecoFipe)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

Exemplo_App_NetCore_Dapper/Views/Veiculos/Edit.cshtml
@model Exemplo_App_NetCore_Dapper.Models.Veiculo_Modelo

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Veiculo_Modelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.DropDownList("Marca", ViewBag.Marcas as SelectList)

                @Html.HiddenFor(item => item.Dados_Marca)
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoFipe" class="control-label"></label>
                <input asp-for="PrecoFipe" class="form-control" />
                <span asp-validation-for="PrecoFipe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Exemplo_App_NetCore_Dapper/Views/Veiculos/Index.cshtml
@model IEnumerable<Exemplo_App_NetCore_Dapper.Models.Veiculo_Modelo>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Cadastrar Novo Veículo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dados_Marca.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecoFipe)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dados_Marca.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecoFipe)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { item.Id }) |
                @Html.ActionLink("Details", "Details", new { item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { item.Id})
            </td>
        </tr>
        }
    </tbody>
</table>